name: Docker Image Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker buildx build -t my-custom-php-image:latest -f MyDockerfile.dockerfile .
    - name: Images
      run: |
        docker images
      
    - name: Run Docker Container
      run: docker run -d my-custom-php-image:latest
